# Generated by Django 5.1.2 on 2024-11-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitimas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Médico', 'Médico'), ('Psicológico', 'Psicológico'), ('Veterinário', 'Veterinário')], max_length=20)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('voluntario_tipo', models.CharField(choices=[('Medico', 'Medico'), ('Psicologo', 'Psicologo'), ('Veterinario', 'Veterinario'), ('Atendente', 'Atendente')], max_length=20)),
                ('voluntario_id', models.PositiveIntegerField()),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitimas.pessoa')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitimas.pet')),
            ],
        ),
    ]
