# Generated by Django 5.1.2 on 2024-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_remove_atendimento_vitima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='voluntario',
            new_name='medico',
        ),
    ]
