# Generated by Django 5.1.2 on 2024-12-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
        ('atendimentos', '0005_rename_voluntario_atendimento_medico'),
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='abrigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocações_abrigo', to='abrigos.abrigo'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocações_atendente', to='voluntarios.atendente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(choices=[('Médico', 'Médico'), ('Psicológico', 'Psicológico'), ('Veterinário', 'Veterinário'), ('Alocação', 'Alocação')], default='Médico', max_length=20),
        ),
    ]
