# Generated by Django 5.1.2 on 2024-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitimas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Peixe', 'Peixe'), ('Outro', 'Outro')], default='Cachorro', max_length=20),
        ),
    ]
