# Generated by Django 5.1.2 on 2024-11-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('capacidade_maxima', models.IntegerField()),
                ('capacidade_maxima_voluntarios', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AbrigoComAnimais',
            fields=[
                ('abrigo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abrigos.abrigo')),
                ('capacidade_maxima_animais', models.IntegerField()),
            ],
            bases=('abrigos.abrigo',),
        ),
    ]
